# This dictionary maps easy to remember names to Youtube video IDs
# after adding an ID here, you can use the {{youtube <shortname>}}
# syntax in your markdown files to embed the video into the page!
videos = Dict(
              "course-intro" => "vxjRWtWoD_w",
              "installation" => "OOjKEgbt8AI",
              "array-intro"  => "CwDI-YOjWhc",
              "cute-one"     => "foN1_hAGfNg",
              "images-intro" => "DGojI9xcCfg",
              "convolution"  => "8rrHTtUzyZA",
              "ted-talk"     => "qGW0GT1rCvs",
              "image-seam"   => "rpB6zQNsbQU",
              "array-views"  => "gTGJ80HayK0",
              "image-seam-reminiscing" => "IQxN1Q8W6bI",
              "james-image-seam" => "ALcohd1q3dk",
              "conv-gpus"    => "aa3JkX_cj_I",
              "conv-real-world" => "e6WnzfvnFlY",
              "types"        => "yU8P_cHPn8Q",
              "dispatch"     => "DXtbaSP_LFI",
              "ides"         => "PgeLMzw_-Ww",
              "structure"    => "ConoBmjlivs",
              "macros-intro" => "e6LGMeoQhfs",
              "understanding-data" => "KrQV6mZ8hvI",
              "introspection" => "IuOXXQR7dAo",
              "covid-data" => "m1dmT-31Qwc",
              "dataframes" => "Pt8Iz4Udg2E",
              "functions-are-objects" => "_O-HBDZMLrM",
              "covid-live" => "Yx055xdSkx0",
              "computational-illustrated" => "6bBFkBCzwh4",
              "matrix-graphs" => "zxHVpNnFt1U",
              "verbs-nouns" => "LvoLXE0U5og",
              "grant-epidemic" => "ErO_Hy01X98",
              "r0"           => "VNo5WrKZ8Yc",
              "self-doc"     => "MQoE69CbfHo",
              "paramtypes"   => "2WVFvRfocjI",
              "raytracing1"  => "MkkZb5V6HqM",
              "byop"         => "dczkYlOM2sg",
              "what-is-array" => "gUZVpMUY4qY",
)
