book_model = [
    Chapter(1, "Images, Transformations, Abstractions"),
    Section(1, 1, "Images as Data and Arrays", "notebooks/week1/images.jl", "3zTO3LEY-cM"),
    Section(1, 2, "Intro to Abstractions", "notebooks/week1/abstraction.jl", "3zTO3LEY-cM"),
    Section(
        1,
        3,
        "Transformations & Autodiff",
        "notebooks/week2/transformations_and_autodiff.jl",
        "AAREeuaKCic",
    ),
    Section(
        1,
        4,
        "Transformations with Images",
        "notebooks/week2/transforming_images.jl",
        "uZYVjDDZW9A",
    ),
    Section(
        1,
        5,
        "Transformations II: Composability, Linearity and Nonlinearity",
        "notebooks/week3/transformations2.jl",
        "VDPf3RjoCpY",
    ),
    Section(1, 6, "The Newton Method", "notebooks/week3/newton_method.jl", "Wjcx9sNSLP8"),
    Section(1, 7, "Intro to Dynamic Programming", "notebooks/week4/dynamicprograms.jl", "KyBXJV1zFlo"),
    Section(1, 8, "Seam Carving", "notebooks/week4/seamcarving.jl", "KyBXJV1zFlo"),
    Section(1, 9, "Taking Advantage of Structure", "notebooks/week4/structure.jl", "wZrVxbmX218"),

    Chapter(2, "Statistics, Probability, Learning"),
    Section(2, 1, "Principal Component Analysis", "notebooks/week5/pca.jl", "iuKrM_NzxCk"),
    Section(2, 2, "Sampling and Random Variables", "notebooks/week5/random_vars.jl", "7HrpoFZzITI"),
    Section(2, 3, "Modeling with Stochastic Simulation", "notebooks/week6/simulating_component_failure.jl", "d8BohH76C7E"),
    Section(2, 4, "Random Variables as Types", "notebooks/week7/random_variables_as_types.jl", "xKAO38UsXo0"),
    Section(2, 5, "Random Walks", "notebooks/week7/random_walks.jl", "14hHtGJ4s-g"),
    Section(2, 6, "Random Walks II", "notebooks/week8/random_walks_II.jl", "pIAFHyLmwbM"),
    Section(2, 7, "Discrete and Continuous", "notebooks/week8/discrete_and_continuous.jl", "H6Dcx3YeTkE"),
    Section(2, 8, "Linear Model, Data Science, & Simulations", "notebooks/week9/linearmodel_datascience.jl","O6NTKsR8TjQ"),
    Section(2, 9, "Optimization", "notebooks/week9/optimization.jl","44RA9fclTdA"),
    
    Chapter(3, "Differential Equations & Climate Modeling"),
    Section(3, 1, "Time stepping", "notebooks/week10/time_stepping.jl", "3Y5gVyO8KcI"),
    Section(3, 2, "ODEs and parameterized types", "notebooks/week11/odes_and_parameterized_types.jl", "S71YIZ8e7MQ"),
    Section(3, 3, "Why we can't predict the weather", "notebooks/week11/predicting_the_weather.jl", "M3udLzIHtsc"), 
    Section(3, 4, "Our first climate model", "notebooks/week12/our_first_climate_model.jl", "J1UsMa1cTeE"),
    Section(3, 5, "How to collaborate on software", "notebooks/week12/how_to_collaborate_on_software.jl", ""),


]
